name: Fetch news & build

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    paths:
      - "scripts/fetch_news.py"
      - "config/feeds.yml"
      - ".github/workflows/fetch.yml"

permissions:
  contents: write
  pages: write
  id-token: write

# <<< ADICIONA ISTO >>>
concurrency:
  group: pages-${{ github.ref }}          # 1 grupo por branch
  cancel-in-progress: true                # cancela corridas pendentes

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil pyyaml
          sudo apt-get update && sudo apt-get install -y jq
      - name: Run fetch script
        run: |
          set -e
          python scripts/fetch_news.py --days 7
          test -s noticias.json || (echo "noticias.json não gerado"; exit 2)
          jq . noticias.json | head -n 40 || true
      - name: Commit changes (if any)
        run: |
          set -e
          if ! git diff --quiet noticias.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add noticias.json
            git commit -m "chore: update noticias.json [skip ci]"
            git push
          else
            echo "Sem alterações."
          fi

  build-deploy:
    needs: fetch
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build and deploy to GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.8
        with:
          jekyll_src: .
        # <<< ADICIONA ISTO >>>
        continue-on-error: true  # ignora o 400 "já terminou"
