name: Fetch news & build

on:
  schedule:
    - cron: "*/30 6-22 * * 1-5" # a cada 30 min, 06:00-22:59 UTC, seg-sex
    - cron: "0 9-20 * * 0,6"   # de hora em hora, 09:00-20:59 UTC, sáb-dom
  workflow_dispatch:
  push:
    paths:
      - "scripts/fetch_news.py"
      - "config/feeds.yml"
      - ".github/workflows/fetch.yml"

permissions:
  contents: write   # necessário para fazer commit
  pages: write
  id-token: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil pyyaml

      - name: Run fetch script
        run: |
          set -e
          python scripts/fetch_news.py --days 7
          test -s noticias.json || (echo "noticias.json não gerado"; exit 2)
          jq . noticias.json | head -n 40 || true  # debug opcional

      - name: Commit changes (if any)
        run: |
          set -e
          if ! git diff --quiet noticias.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add noticias.json
            git commit -m "chore: update noticias.json [skip ci]"
            git push
          else
            echo "Sem alterações."
          fi

  build-deploy:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy to GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.8
        with:
          jekyll_src: .
