name: Build noticias.json

on:
  schedule:
    # Corre todos os dias, de hora a hora (em UTC)
    - cron: '0 * * * *'
  workflow_dispatch: {}   # Permite correr manualmente também

permissions:
  contents: write

jobs:
  build-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pytz python-dateutil pyyaml

      - name: Generate noticias.json
        run: |
          python scripts/fetch_news.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add noticias.json
            git commit -m "chore: update noticias.json [auto]"
            git push
          else
            echo "No changes to commit."
          fi
